.\" mlclient.1   -*- nroff -*-
.TH MLCLIENT 1 "2004-10-24"
.SH NAME
mlclient \- client for mlterm
.SH SYNOPSIS
.B mlclient
.RB [\fIoptions\fP]
.\" ********************************************************************
.SH DESCRIPTION
\fBmlclient\fR is a client for the \fBmlterm\fR(1) server (daemon).
\fBmlterm\fR(1), an X terminal emulator, can be invoked
as a daemon process which holds multiple sessions (shell process and other
informations like backlog).  \fBmlclient\fR can creat a new session
or recall an existing session which had been disconnected from a window.
.\" ********************************************************************
.SH OPTIONS
\fBmlclient\fR accepts most options of mlterm.
Please read \fBmlterm\fR(1) for detail.

Following options do \fBnot\fR work for \fBmlclient\fR:
.TP
\fB\-K\fR/\fB\-\-maxptys\fR,
.TP
\fB\-P\fR/\fB\-\-ptys\fR,
.TP
\fB\-R\fR/\fB\-\-fsrange\fR,
.TP
\fB\-W\fR/\fB\-\-sep\fR,
.TP
\fB\-Y\fR/\fB\-\-decsp\fR,
.TP
\fB\-c\fR/\fB\-\-cp932\fR,
.TP
\fB\-i\fR/\fB\-\-xim\fR, and
.TP
\fB\-j\fR/\fB\-\-daemon\fR
.\" ********************************************************************
.SH SEE ALSO
\fBmlterm\fR(1),
\fBlocale\fR(7),
\fBcharsets\fR(7),
\fBUTF-8\fR(7), and
\fBX\fR(7).
.\" ********************************************************************
.SH CONTACT
Subscribe mlterm-dev-en ML
(http://lists.sourceforge.net/lists/listinfo/mlterm-dev-en).

