.\" mlcc.1   -*- nroff -*-
.TH MLCC 1 "2018-10-27"
.SH NAME
mlcc \- simple configurator for mlterm
.SH SYNOPSIS
.B mlcc
.RB [\fIoptions\fP]
.RB [\fIarguments\fP]
.\" ********************************************************************
.SH DESCRIPTION
\fBmlcc\fR is a helper to configure \fBmlterm\fR(1) by sending special escape sequences.
.nf
(See http://bitbucket.org/arakiken/mlterm/src/tip/doc/en/PROTOCOL)

.\" ********************************************************************
.SH OPTIONS
\fB\-h\fR, \fB\-\-help\fR
Show help messages.

.\" ********************************************************************
.SH EXAMPLE
.TP
\fBmlcc\fR
.nf
Show configuration screen.
.TP
\fBmlcc fg_color blue\fR
Change the value of "fg_color" option to "blue".
.TP
\fBmlcc exec full_reset\fR
Execute "full_reset" command.
.TP
\fBmlcc aafont ISO10646_UCS4_1 Courier\fR
Change font name of "ISO10646_UCS4_1" in aafont configuration to "Courier".
.TP
\fBmlcc color red rgb:ff/00/00\fR
Change RGB of "red" to rgb:ff/00/00.
.\" ********************************************************************
.SH SEE ALSO
\fBmlterm\fR(1),
.\" ********************************************************************
.SH CONTACT
Subscribe mlterm-dev-en ML
(http://lists.sourceforge.net/lists/listinfo/mlterm-dev-en).
