name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: setup build environment
      run: |
        case "${{ matrix.os }}" in
        ubuntu*)
          sudo apt update; sudo apt install -y libgtk-3-dev libvterm-dev libvte-2.91-dev libsdl2-dev libfribidi-dev libuim-dev libfcitx5core-dev libfcitx5gclient-dev libscim-dev libssh2-1-dev curl
          ;;
        macos*)
          brew install pkg-config
          ;;
        esac

    - name: configure
      run: |
        case "${{ matrix.os }}" in
        ubuntu*)
          (cd uitoolkit/wayland && sh ./rescanproto.sh)
          CONFIGURE_ARGS="--with-gui=xlib,fb,console,wayland,sdl2"
          ;;
        macos*)
          CONFIGURE_ARGS="--with-gui=quartz"
          ;;
        esac
        CFLAGS="-Wall -g -O2" ./configure ${CONFIGURE_ARGS}

    - name: build
      run: |
        make
        sudo make install
        case "${{ matrix.os }}" in
        ubuntu*)
          (cd gtk && make && sudo make install)
          (cd libvterm && make && sudo make install)
          ;;
        macos*)
          ;;
        esac

  build-netbsd:
    name: "build-netbsd (NetBSD/amd64 10.0 with pkgsrc)"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install packages and run configure and make (on the NetBSD VM)
        uses: vmactions/netbsd-vm@v1
        with:
          release: "10.0"
          usesh: true
          copyback: false
          prepare: |
            PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R7/bin:/usr/pkg/bin:/usr/pkg/sbin:/usr/games:/usr/local/bin:/usr/local/sbin
            export PATH
            ftp -o - https://cdn.NetBSD.org/pub/NetBSD/NetBSD-`uname -r`/amd64/binary/sets/xbase.tar.xz | tar -C / -zxpf - ./usr/X11R7/bin ./usr/X11R7/include ./usr/X11R7/lib ./usr/X11R7/share
            ftp -o - https://cdn.NetBSD.org/pub/NetBSD/NetBSD-`uname -r`/amd64/binary/sets/xcomp.tar.xz | tar -C / -zxpf - ./usr/X11R7/bin ./usr/X11R7/include ./usr/X11R7/lib ./usr/X11R7/share
            pkg_add -u pkgconf gettext-tools libtool-base
            pkg_add -u cairo Canna-lib fribidi gdk-pixbuf2 gtk3+ fcitx ibus m17n-lib harfbuzz scim uim ja-FreeWnn-lib libXft SDL2 libssh2 vte3
          run: |
            PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R7/bin:/usr/pkg/bin:/usr/pkg/sbin:/usr/games:/usr/local/bin:/usr/local/sbin
            export PATH
            CFLAGS="-Wall -g -O2" CPPFLAGS="-I/usr/pkg/include" ./configure --x-includes=/usr/X11R7/include --x-libraries=/usr/X11R7/lib --with-imagelib=gdk-pixbuf --with-gui=xlib,wscons,sdl2 --with-type-engins=xcore,xft,cairo --enable-anti-alias
            make
            make install
